#Write a Python program to check if all dictionaries in a list are empty or not.

In [1]:
list1=[{},{},{}]
list2=[{'a','b'},{2,3,4},{8,'g'},{}]
print(all(not x for x in list1))
print(all(not x for x in list2))

True
False


#Write a Python program to remove duplicates from a list of lists.

In [2]:
l1=['a','b','a','c','c']
l1=list(dict.fromkeys(l1))
print(l1)

['a', 'b', 'c']


In [3]:
import itertools
num=[[110, 120], [240], [330, 456, 425], [310, 220], [133], [240]]
#num=list(dict.fromkeys(num))
print("Original__List",num)
num.sort()
new_num=list(num for num,_ in itertools.groupby(num))
print("New__List",new_num)
             

Original__List [[110, 120], [240], [330, 456, 425], [310, 220], [133], [240]]
New__List [[110, 120], [133], [240], [310, 220], [330, 456, 425]]


Write a Python program to extend a list without append.

In [4]:
x=[100,120,87]
y=[342,65,789]
x[:0]=y
print(x)

[342, 65, 789, 100, 120, 87]


In [5]:
x=[100,120,87]
y=[342,65,789]
#y[:0]=x
print(x+y)

[100, 120, 87, 342, 65, 789]


Write a Python program to find the list in a list of lists whose sum of elements is the highest.

In [6]:
l1=[[2,3,4],[4,5,8],[10,11,21]]
print(max(l1))

[10, 11, 21]


In [7]:
l=[[2,3,10],[10,23,3],[323,4,1],[9,8,7]]
print(max(l,key=sum))

[323, 4, 1]


#Write aPython program to access dictionary key’s element by index.

In [8]:
my_dict={"name":"Tulsi","surname":"jha","age":20}
print(list(my_dict))

['name', 'surname', 'age']


In [9]:
print(list(my_dict)[0])

name


#Write a Python program to iterate over two lists simultaneously.

In [10]:
num=[1,2,3]
color=['rad','white','black']
for (a,b) in zip(l1,l2):
    print(a,b)

NameError: name 'l2' is not defined

In [11]:
l1=[2,3,4,5]
l2=['a','b','c','d']
for (i,j) in zip(l1,l2):#lPython program to iterate over two lists simultaneously.2):
    print(i,j)

2 a
3 b
4 c
5 d


In [12]:
a=print("Hello")

Hello


In [13]:
s=['america','india']
v=['play','watch']
o=['baseball','cricket']
def fo():
    for i in s:
        for j in v:
            for k in o:
                print(i,j,k)
fo()

america play baseball
america play cricket
america watch baseball
america watch cricket
india play baseball
india play cricket
india watch baseball
india watch cricket


In [14]:
import pandas as pd

In [15]:
data=pd.read_csv('ex5.csv')
data

FileNotFoundError: [Errno 2] File ex5.csv does not exist: 'ex5.csv'

In [ ]:
dt=pd.date_range('1/1/2000',periods=70)
dt

In [ ]:
import csv
f=open('ex7.csv')

reader=csv.reader(f)
reader

In [ ]:
l1=[2,3,4,6,7]
l2=['a',8,9,10,'b']
for (i,j) in zip(l1,l2):
    print(i,j)

In [ ]:
l1={'k1':'a','k2':'b','k3':'c'}
l2={'l2':'L1','l2':"L2","l3":'L3'}
for (i,j) in zip(l1,l2):
    print(i,j)

In [ ]:
{a:b for (a,b) in zip(l1,l2)}

In [ ]:
import requests
url="api.github.com/users"
reps=requests.get("api.github.com/users")

In [ ]:
n=int(input("INPUT  "))
s=0
for i in range(n+1):
   # s=0
    s=s+i
print("Sum of ",n,'is',s)

In [ ]:
n=int(input(" Enter Input  "))
s=0
while True:
    s=s+n
print(s)
    

In [ ]:
2+3

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:


df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN',
'londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})

df

In [ ]:
df.head(10)

In [ ]:
df

In [ ]:
df['FlightNumber'][0]+10

In [ ]:
df

In [ ]:
#NUMPY ASSIGNMENT


In [ ]:
l=[10,20,30,40,50,60,70,80,90,100]
for i in l:
    a,b,c,d=10,20,30,40
    #e=(10+20+30+40)/4
    while True:
        
        #e=(a+b+c+d)/4
        a=b
        b=c
        c=d
        d=c+10
        e=(a+b+c+d)/4
    #print(e)
print(e)

In [ ]:
l=[10,20,30,40,50,60,70,80,90,100]
while True:
    a,b,c,d=10,20,30,40,50
    return d

In [ ]:
l=[10,20,30,40,50,60,70,80,90,100]
def true():
    a,b,c,d=10,20,30,40
    e=d+10
    while e>0:
        a,b,c,d,e=a,b,c,d,e
        while True:
            return a,b,c,d,e,a,b,c,d,e

In [ ]:
true()

In [ ]:
l

In [35]:
y1=(3+5+7)/3
y2=(5+7+2)/3
y3=(7+2+8)/3
y4=(2+8+10)/3
y5=(8+10+11)/3
y6=(10+11+65)/3
y7=(11+65+72)/3
y8=(65+72+81)/3
y9=(72+82+99)/3
y10=(82+99+100)/3
y11=(99+100+150)/3

In [38]:
print(y1,'\n',y2,'\n',y3,'\n',y4,'\n',y5,'\n',y6,'\n',y7,'\n',y8,'\n',y9,'\n',y10,'\n',y11)

5.0 
 4.666666666666667 
 5.666666666666667 
 6.666666666666667 
 9.666666666666666 
 28.666666666666668 
 49.333333333333336 
 72.66666666666667 
 84.33333333333333 
 93.66666666666667 
 116.33333333333333


In [ ]:
l[0:10]

In [ ]:
def swap():
    while True:
        
        a,b,c,d=10,20,30,40
        e=d+10
        for i in l:
            d1=(a+b+c+d)/4
            d2=(b+c+d+e)/4
            d3=(c+d+e+e+10)/4
            d4=()/4
            return d1,d2,d3,d4

In [ ]:
swap()

In [4]:
import numpy as np

def moving_average(data_set, periods=3):
    weights = np.ones(periods) / periods
    return np.convolve(data_set, weights, mode='valid')

data = [1, 2, 3, 6, 9, 12, 20, 28, 30, 25, 22, 20, 15, 12, 10]

ma = moving_average(np.asarray(data), 3)
assert (np.around(ma, decimals=2)==np.array([2.0, 3.67, 6.0, 9.0, 13.67, 20.0, 26.0, 27.67, 25.67, 22.33, 19.0, 15.67, 12.33])).all() == True

In [5]:
ma

array([ 2.        ,  3.66666667,  6.        ,  9.        , 13.66666667,
       20.        , 26.        , 27.66666667, 25.66666667, 22.33333333,
       19.        , 15.66666667, 12.33333333])

In [20]:
def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w

In [21]:
x = np.array([5,3,8,10,2,1,5,1,0,2])

In [22]:
x

array([ 5,  3,  8, 10,  2,  1,  5,  1,  0,  2])

In [23]:
moving_average(x, 2)

array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])

In [24]:
def moving_average(l,w):
    return np.convolve(l,np.ones(w),'valid')/w

In [26]:
l=np.array([10,20,30,40,50,60,70,80,90,100])
l

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
moving_average(l,4)

array([25., 35., 45., 55., 65., 75., 85.])

In [29]:
L=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
L

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [32]:
def Moving_Average(L,W):
    return np.convolve(L,np.ones(W),'valid')/W

In [33]:
Moving_Average(L,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])