# Numpy Array

In [2]:

import numpy as np
np.array(['bcd',1,2,4,6,'bcd'])

array(['bcd', '1', '2', '4', '6', 'bcd'], dtype='<U3')

In [3]:
type(np.array(['bcd',1,2,4,6,'bcd']))

numpy.ndarray

In [4]:
np.array((2,3,4))

array([2, 3, 4])

In [5]:
np.array([2,3,6.])

array([2., 3., 6.])

In [6]:
np.array([[3,4],[7,8]])

array([[3, 4],
       [7, 8]])

In [7]:
np.array(((5,6.),(5,8)))

array([[5., 6.],
       [5., 8.]])

In [8]:
#maximum dimension 2:

np.array([2,'gn'])

array(['2', 'gn'], dtype='<U11')

In [9]:
np.array([[[[3,4,5,6]]]])

array([[[[3, 4, 5, 6]]]])

In [10]:
np.array([3,4,5],ndmin=5)

array([[[[[3, 4, 5]]]]])

In [11]:
np.array([4,4,56,89],dtype=complex)

array([ 4.+0.j,  4.+0.j, 56.+0.j, 89.+0.j])

In [12]:
np.array((3,4,5),copy=False)

array([3, 4, 5])

In [13]:
dir(np.array([3,4]))

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [14]:
x=np.array([(2,3),(4,5)],dtype=[('a','<i2'),('b','<i8')])
x

array([(2, 3), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [15]:
type(x)

numpy.ndarray

In [16]:
type(x[0][1])

numpy.int64

In [17]:
type(x[1][1])

numpy.int64

In [18]:
#creating array from the sub-classes


np.mat(np.array([[2,3,4],[9,8,7]]))

matrix([[2, 3, 4],
        [9, 8, 7]])

In [19]:
np.matrix([[3,4,5],[9,7,4]])

matrix([[3, 4, 5],
        [9, 7, 4]])

In [22]:
np.matrix(((2,3.,5),(6,5,4)))

matrix([[2., 3., 5.],
        [6., 5., 4.]])

In [24]:
##v/s bfor nd after dec(.)

np.matrix([[2,.3,4],[0,9,8]])

matrix([[2. , 0.3, 4. ],
        [0. , 9. , 8. ]])

In [60]:
np.mat(([4,3,2],[4,5,9.]))

matrix([[4., 3., 2.],
        [4., 5., 9.]])

In [26]:
np.mat(((1,2,3),(3,4,5)))

matrix([[1, 2, 3],
        [3, 4, 5]])

In [27]:
np.matrix(((2,3,4,5),(6,7,8,9)))

matrix([[2, 3, 4, 5],
        [6, 7, 8, 9]])

In [28]:
#np.matrix(((2,3,4,5),(6,7,8,9)))
#np.mat(((1,2,3),(3,4,5)))

In [64]:
a=np.mat('1,2,3;6,7,8')
a

matrix([[1, 2, 3],
        [6, 7, 8]])

In [65]:
type(a)

numpy.matrix

In [67]:
np.mat('2,3;6,5')

matrix([[2, 3],
        [6, 5]])

# Numpy Asarray

In [ ]:
#convert input into array
#convery list into array

In [70]:
a=[3,4,'hj']
print(a)

[3, 4, 'hj']


In [71]:
type(a)

list

In [73]:
b=np.array(a)
type(b)

numpy.ndarray

In [75]:
np.asarray([2,3,4])


array([2, 3, 4])

In [76]:
type(np.asarray(a))

numpy.ndarray

In [77]:
a=np.asarray([2,3,4])
type(a)

numpy.ndarray

In [78]:
np.asarray((2,3,4))

array([2, 3, 4])

In [89]:
a1=np.array([99,8,7,6],dtype=float)
a1

array([99.,  8.,  7.,  6.])

In [90]:
np.array([9,8,7,6],dtype=np.float32)

array([9., 8., 7., 6.], dtype=float32)

In [94]:
np.asarray([2,3,4]) is a1

False

In [95]:
np.array([2,3,4]) is a1

False

In [98]:
np.array(a1,dtype=np.float32) is a1

False

In [99]:
#ndarray sub-classes are not apssed through

In [100]:
issubclass(np.matrix,np.ndarray)

True

In [102]:
a=np.mat([[2,34,5]])
np.asarray(a)

array([[ 2, 34,  5]])

In [103]:
a=np.mat([[2,34,5]])
np.asanyarray(a)

matrix([[ 2, 34,  5]])

In [104]:
np.asarray(a) is a

False

In [106]:
np.asanyarray(a) is a

True

In [108]:
type(np.asarray(a))

numpy.ndarray

# numpy asanyarray


In [118]:
a=[21,12,23]
np.array(a)

array([21, 12, 23])

In [119]:
np.asarray(a)

array([21, 12, 23])

In [120]:
np.asanyarray(a)

array([21, 12, 23])

In [121]:
a1=np.matrix([2,3])
a1

matrix([[2, 3]])

In [122]:
np.asanyarray([21,12,23]) is a

False

In [123]:
#numpy .copy

In [125]:
np.array(a,copy=True)

array([21, 12, 23])

In [126]:
#Create an array x, with a reference y and a copy z:

In [29]:
x=np.array([2,3,4,1])
x


array([2, 3, 4, 1])

In [30]:
##What is the reason behind this??

y

NameError: name 'y' is not defined

In [31]:
y=x
y

array([2, 3, 4, 1])

In [32]:
z=np.copy(x)
z

array([2, 3, 4, 1])

In [33]:
z=np.copy(y)
z

array([2, 3, 4, 1])

In [34]:
y[0]

2

In [35]:
y[0]=100
y

array([100,   3,   4,   1])

In [36]:
y

array([100,   3,   4,   1])

In [144]:
x[2]

4

In [148]:
x[2]=1000
y

array([ 100,    3, 1000,    1])

In [149]:
z

array([2, 3, 4, 1])

In [150]:
id(x[0])

2013167033904

In [151]:
id(y[0])

2013167034096

In [13]:
print(np.zeros((3,4,8))+5*2)

[[[10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]]

 [[10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]]

 [[10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10. 10. 10.]]]


In [9]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [12]:
l=[2,3,4,5]
np.asanyarray(l)

array([2, 3, 4, 5])

In [15]:
np.matrix([[1,2,3],[3,4,5]])

matrix([[1, 2, 3],
        [3, 4, 5]])

In [17]:
a=np.ones((4,5,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
a.shape

(4, 5, 2)

In [19]:
a.size

40

In [23]:
a.ndim

3

In [25]:
x=np.ones((3,3,3))
y=np.ones((3,3,3))+5
x+y

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])

In [26]:
#TASK----1
"""
1.print(np.zeros((3,4,8))+5*2)
2.np.linspace(4,8,80)
3.np.matrix([[1,2,3],[3,4,5]])
4.a=np.ones((4,5,2))
a
a.shape
a.size
a.dtype
a.ndim
5.x=np.ones((3,3,3))
y=np.ones((3,3,3))+5
x+y

"""

'\n1.print(np.zeros((3,4,8))+5*2)\n2.np.linspace(4,8,80)\n3.np.matrix([[1,2,3],[3,4,5]])\n4.a=np.ones((4,5,2))\na\na.shape\na.size\na.dtype\na.ndim\n5.x=np.ones((3,3,3))\ny=np.ones((3,3,3))+5\nx+y\n\n'

In [1]:
import numpy as np
import pandas as pd

In [2]:
Input=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
MAT=np.matrix(Input)
MAT

matrix([[  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150]])

In [3]:
y1=(3+5+7)/3
y2=(5+7+2)/3
y3=(7+2+8)/3
y4=(2+8+10)/3
y5=(8+10+11)/3
y6=(10+11+65)/3
y7=(11+65+72)/3
y8=(65+72+81)/3
y9=(72+81+99)/3
y10=(81+99+100)/3
y11=(99+100+150)/3

In [17]:
print('\n','y1=',y1,'\n','y2=',y2,'\n','y3=',y3,'\n','y4=',y4,'\n','y5=',y5,'\n','y6=',y6,'\n','y7=',y7,'\n','y8=',y8,'\n','y9=',y9,'\n','y10=',y10,'\n','y11=',y11)


 y1= 5.0 
 y2= 4.666666666666667 
 y3= 5.666666666666667 
 y4= 6.666666666666667 
 y5= 9.666666666666666 
 y6= 28.666666666666668 
 y7= 49.333333333333336 
 y8= 72.66666666666667 
 y9= 84.0 
 y10= 93.33333333333333 
 y11= 116.33333333333333


In [22]:
MAT=np.matrix((y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11))

In [23]:
MAT

matrix([[  5.        ,   4.66666667,   5.66666667,   6.66666667,
           9.66666667,  28.66666667,  49.33333333,  72.66666667,
          84.        ,  93.33333333, 116.33333333]])

In [24]:
Input

[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [ ]:
for i in range(len(Input)):
    

In [152]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [156]:
x=np.arange(16).shape
x

(16,)

In [157]:
x=np.arange(16).reshape(-49898,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [158]:
x.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [159]:
np.diag(x)

array([ 0,  5, 10, 15])

In [160]:
np.diag(x,k=-1)

array([ 4,  9, 14])